### ISSUE TITLE
'RCTBridgeModule.h' file not found (RN@0.36.0)

### ISSUE THREAD

**Issue by duailibe** [tinycreative/react-native-intercom#72]
The project is failing to compile for iOS with the following error:

```
[...]/node_modules/react-native-intercom/iOS/IntercomWrapper.h:13:9: fatal error: 'RCTBridgeModule.h' file not found
#import "RCTBridgeModule.h"
        ^
```

What fixed for us was this diff:
https://github.com/tinycreative/react-native-intercom/compare/master...projetoeureka:master

I'm not sure if there's something special with our setup, but since no one else complained about this, I'm creating an issue first and I'll happily open up a PR.

Thanks

**Comment by browniefed** [comment]
We've attempted to make this backwards compatible but React Native changed their header structure in .40 so this may be broken on older versions.

**Comment by duailibe** [comment]
I know that. The thing is, I'm not sure what `node_modules/react-native/React/**/**` means in the search path. I do understand `node_modules/react-native/React/**` but I don't have enough Xcode experience to know which one's right.

I just know one works with RN 0.36.0 and the other doesn't. Haven't tested with a RN >= 0.40.0 app.

**Comment by browniefed** [comment]
I believe both are in the search paths now, but if you can make it work with a particular search path then feel free and add it and submit a PR.

**Comment by duailibe** [comment]
They are not, but I opened a PR anyway.

Thanks!

**Comment by rkang** [comment]
I recently had this issue and had to manually link the react native intercom to our project to solve the issue.
